---
title: "Assessing population shifts following open data policies"
author: "Tom"
date: "2/4/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(viridis)
library(knitr)
set.seed(123) # set random seed
btstrp.N <- 999 # number of bootstrap samples
```

# PSYCHOLOGICAL SCIENCE

```{r, include = FALSE}
## Mike Code:
d <- read_csv("AuthorList.csv")

authors <- d %>%
  group_by(author) %>%
  count

d %>% 
  group_by(year) %>%
  summarise(n_papers = length(unique(article_id)), 
            n_authors = length(author),
            n_authors_per_paper = n_authors / n_papers,
            n_unique_authors = length(unique(author))) %>%
  kable(digits = 2)


unique_authors <- d %>% 
  select(-article_id) %>%
  distinct
  
overlaps <- d %>%
  split(.$year) %>%
  map_df(function(x) {
    this_year_authors = unique(x$author)
    overlap <- unique_authors %>% 
      group_by(year) %>% 
      summarise(overlap = sum(author %in% this_year_authors), 
                dice = (2 * overlap) / (length(author) + length(this_year_authors))) %>%
      mutate(source_year = x$year[1])
  }) %>%
  mutate(overlap = ifelse(year == source_year, NA, overlap),
         dice = ifelse(year == source_year, NA, dice))

ggplot(filter(overlaps, year > 2008 & year < 2018, 
              source_year > 2008 & source_year < 2018), 
       aes(x = year, y = source_year, fill = dice)) + 
  geom_tile() + 
  xlim(2009,2018) + 
  scale_fill_viridis() + 
  theme_bw()
```

## Tom code:

Function to calculate dice coefficient:

```{r}
dice <- function(vector1, vector2){
  v1 <- unique(vector1) # select only unique elements
  v2 <- unique(vector2) # select only unique elements
  
  overlap <- intersect(v1, v2) # find elements that are present in both vectors
  overlapN <- length(overlap) # find number of overlapping elements
  
  v1N <- length(v1) # get length of vector 1
  v2N <- length(v2) # get length of vector 2
  
  diceCoeff <- (2*overlapN) / (v2N + v1N) # calculate dice coefficient
  
  return(diceCoeff)
}
```

Function to generate samples with replacement and calculate dice each time:

```{r}
bootDice <- function(v1, v2) {
  v1_new <- sample(v1, size = length(v1), replace = T)
  v2_new <- sample(v2, size = length(v2), replace = T)
  return(dice(v1_new, v2_new))
}
```

Wrapper function uses dice() and bootDice() to calculate Dice coefficent between authors publishing target year and previous 3 years:

```{r}
rollingDice <- function(targetYear){
  
  previousYears <- as.character(c(targetYear-1, targetYear-2, targetYear-3)) # get list of previous 3 years
  targetYear <- as.character(targetYear) # target year as character
  
  targetAuthors <- d %>% filter(year == targetYear) %>% pull(author) # select authors in target year
  previousAuthors <- d %>% filter(year %in% previousYears) %>% pull(author) # select authors in previous three years
  
  diceOut <- dice(targetAuthors, previousAuthors) # get dice coefficient

  myDice <- replicate(btstrp.N, bootDice(targetAuthors, previousAuthors)) # bootstrap
  diceCI <- quantile(myDice, c(.025, .975)) # calculate confidence intervals
  
  outputDF <- data.frame(targetYear = as.numeric(targetYear), dice = diceOut, lwr.ci = diceCI[1], upr.ci = diceCI[2], btstrp.dice.mean = mean((myDice)), row.names = NULL) # combine Dice, CIs, and the mean dice for bootstrapped samples
  
  return(outputDF)
}
```

Apply the functions:

```{r}
yearDice <- data.frame(targetYear = seq(2011,2017, 0001)) %>%
  rowwise() %>%
  do(rollingDice(.$targetYear))

kable(yearDice)
```

```{r}
ggplot(data = yearDice) +
  geom_line(aes(x = targetYear, y = dice, group = 1), colour = "indianred1", size = 1.1) +
  geom_vline(xintercept=2014.05) +
  scale_x_continuous(breaks = seq(2011, 2017, 0001), labels = seq(2011, 2017, 0001)) +
  ylim(0,0.2) +
  ylab("Author overlap with previous three years (Dice coeffcient)") +
  xlab("Publication year") +
  ggtitle("Psychological Science") +
  papaja::theme_apa()
```

## COGNITION


```{r, include=FALSE}
d <- read_csv("AuthorList_Cognition.csv")
```

Apply the functions for Cognition:

```{r}
yearDice <- data.frame(targetYear = seq(2008,2017, 0001)) %>%
  rowwise() %>%
  do(rollingDice(.$targetYear))

kable(yearDice)
```


```{r}
ggplot(data = yearDice) +
  geom_line(aes(x = targetYear, y = dice, group = 1), colour = "indianred1", size = 1.1) +
  geom_vline(xintercept=2015.12) +
  scale_x_continuous(breaks = seq(2008, 2017, 0001), labels = seq(2008, 2017, 0001)) +
  ylim(0,0.2) +
  ylab("Author overlap with previous three years (Dice coeffcient)") +
  xlab("Publication year") +
  ggtitle("Cognition") +
  papaja::theme_apa()
```